### ISSUE TITLE
Pls change "getLevel" to "GetLevel" -> Compile error

### ISSUE THREAD

**Issue by cptcl** [azerothcore/mod-account-achievements#15]
Changing all entys from "getLevel" to "GetLevel" in the cpp file in src folder fixed my compilation errors, as of today

**Comment by Helias** [comment]
please open a PR to share the fix

**Comment by Tralenor** [comment]
I think this can be closed, fixed in #16

**Comment by Helias** [comment]
Done, thanks 👍
